'use client';
import { useMemo, useState } from 'react';
import { Card, Stat } from '@/components/ui';
import { CalendarClock, CheckCircle2, CircleDollarSign, Plus, Search, UserRoundCheck, Users } from 'lucide-react';

type Candidate={id:string;name:string;rank:string;experience:string;match:number;status:'Applied'|'Shortlisted'|'Interview'|'Rejected'};
const seed:Candidate[]=[
  {id:'c1',name:'Capt. Rahul Menon',rank:'Master Mariner',experience:'Oil / Product Tankers · 18 years',match:96,status:'Applied'},
  {id:'c2',name:'Priya Nair',rank:'Chief Officer',experience:'LNG / Tankers · 12 years',match:92,status:'Shortlisted'},
  {id:'c3',name:'C/E Arjun Mehta',rank:'Chief Engineer',experience:'Product / Chemical · 16 years',match:86,status:'Interview'},
  {id:'c4',name:'Amit Sharma',rank:'Second Officer',experience:'Tankers · 7 years',match:78,status:'Applied'}
];
export default function RecruiterPage(){
  const [candidates,setCandidates]=useState(seed);const [posting,setPosting]=useState(false);const [query,setQuery]=useState('');
  const filtered=useMemo(()=>candidates.filter(c=>`${c.name} ${c.rank} ${c.experience}`.toLowerCase().includes(query.toLowerCase())),[candidates,query]);
  const move=(id:string,status:Candidate['status'])=>setCandidates(list=>list.map(c=>c.id===id?{...c,status}:c));
  return <div className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="sns-page-title">Recruiter workspace</div><p className="sns-page-copy mt-1">Post roles, evaluate maritime fit, manage the hiring pipeline and schedule interviews from one company dashboard.</p></div><button onClick={()=>setPosting(!posting)} className="sns-button sns-button-primary"><Plus size={16}/>Post a job</button></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat value="12" label="Active jobs" trend="+3 this month"/><Stat value="284" label="Applications" trend="+18.6%"/><Stat value="46" label="Shortlisted" trend="16% conversion"/><Stat value="18" label="Interviews" trend="8 scheduled"/></div>
  {posting&&<Card className="p-5"><div className="flex items-center gap-2 font-black text-[#173b59]"><Plus size={18} className="text-[#1167d8]"/>Create maritime vacancy</div><div className="mt-4 grid gap-3 md:grid-cols-2"><input className="sns-input" placeholder="Role / rank"/><input className="sns-input" placeholder="Vessel type"/><input className="sns-input" placeholder="Contract duration"/><input className="sns-input" placeholder="Salary / currency"/><input className="sns-input" type="date"/><input className="sns-input" placeholder="Experience required"/><input className="sns-input md:col-span-2" placeholder="Certificates required"/><textarea className="sns-input min-h-[96px] md:col-span-2" placeholder="Job description"/></div><div className="mt-3 flex justify-end"><button onClick={()=>setPosting(false)} className="sns-button sns-button-primary">Publish vacancy</button></div></Card>}
  <Card className="p-4"><div className="flex items-center gap-2 rounded-xl border border-[#dbe5ee] px-3"><Search size={17} className="text-[#8195a5]"/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-11 flex-1 outline-none" placeholder="Search candidates by rank, vessel or name"/></div></Card>
  <div className="space-y-3">{filtered.map(c=><Card key={c.id} className="p-5"><div className="flex flex-wrap items-start gap-4"><div className="sns-avatar sns-avatar-md">{c.name.split(' ').slice(-2).map(x=>x[0]).join('').slice(0,2)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-[#173b59]">{c.name}</h2><span className="sns-pill sns-pill-green">{c.match}% fit</span><span className="sns-pill sns-pill-blue">{c.status}</span></div><div className="mt-1 text-sm font-semibold text-[#597487]">{c.rank}</div><div className="mt-1 text-xs text-[#718697]">{c.experience}</div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>move(c.id,'Shortlisted')} className="sns-button sns-button-secondary px-3 py-2 text-xs"><UserRoundCheck size={14}/>Shortlist</button><button onClick={()=>move(c.id,'Interview')} className="sns-button sns-button-secondary px-3 py-2 text-xs"><CalendarClock size={14}/>Schedule interview</button><button onClick={()=>move(c.id,'Rejected')} className="sns-button sns-button-ghost px-3 py-2 text-xs">Reject</button></div></div></div></Card>)}</div>
  <div className="grid gap-3 sm:grid-cols-3"><Card className="p-4"><Users size={18} className="text-[#1167d8]"/><b className="mt-3 block text-[#173b59]">Talent search</b><p className="mt-1 text-xs leading-5 text-[#728799]">Premium access to verified maritime profiles and availability.</p></Card><Card className="p-4"><CheckCircle2 size={18} className="text-[#1167d8]"/><b className="mt-3 block text-[#173b59]">Verified applicants</b><p className="mt-1 text-xs leading-5 text-[#728799]">Surface verified CoC, certificates and professional badges.</p></Card><Card className="p-4"><CircleDollarSign size={18} className="text-[#1167d8]"/><b className="mt-3 block text-[#173b59]">Recruiter plans</b><p className="mt-1 text-xs leading-5 text-[#728799]">Architecture supports job credits, subscriptions and corporate access.</p></Card></div></div>
}
