import { createClient } from '@/lib/supabase/server';
import { currentUser, profiles, posts, jobs, groups, courses, mentors, events, type Profile, type Post, type Job, type Course } from '@/lib/data/seed';

const configured=()=>Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
export async function getCurrentProfile():Promise<Profile>{
  if(!configured()) return currentUser;
  try{const sb=await createClient();const {data:claims}=await sb.auth.getClaims();const id=claims?.claims?.sub as string|undefined;if(!id)return currentUser;const {data}=await sb.from('profiles').select('*').eq('id',id).maybeSingle();if(!data)return currentUser;return {id:data.id,name:data.full_name,initials:(data.full_name||'SN').split(' ').map((x:string)=>x[0]).slice(0,2).join('').toUpperCase(),role:[data.rank,data.current_company].filter(Boolean).join(' · ')||'Maritime Professional',company:data.current_company||'',location:data.location||'',experienceYears:Number(data.sailing_experience_years||0),vesselTypes:data.vessel_types||[],skills:data.skills||[],certificates:Array.isArray(data.certificates)?data.certificates.map((x:any)=>typeof x==='string'?x:x?.name).filter(Boolean):[],verified:data.verification_badge||'',followers:0,connections:0,reputation:data.reputation_points||0,summary:data.professional_summary||'',availability:data.availability||''};}catch{return currentUser;}
}
export async function getFeedData():Promise<{posts:Post[];profiles:Profile[]}>{
  if(!configured())return {posts,profiles};
  try{const sb=await createClient();const [{data:pRows},{data:peopleRows}]=await Promise.all([sb.from('posts').select('id,author_id,category,body,tags,share_count,created_at').eq('status','published').order('created_at',{ascending:false}).limit(30),sb.from('profiles').select('*').limit(100)]);if(!pRows?.length||!peopleRows?.length)return {posts,profiles};const mappedPeople=peopleRows.map((d:any)=>({id:d.id,name:d.full_name,initials:(d.full_name||'SN').split(' ').map((x:string)=>x[0]).slice(0,2).join('').toUpperCase(),role:[d.rank,d.current_company].filter(Boolean).join(' · ')||'Maritime Professional',company:d.current_company||'',location:d.location||'',experienceYears:Number(d.sailing_experience_years||0),vesselTypes:d.vessel_types||[],skills:d.skills||[],certificates:[],verified:d.verification_badge||'',followers:0,connections:0,reputation:d.reputation_points||0,summary:d.professional_summary||'',availability:d.availability||''}));const mappedPosts=pRows.map((d:any)=>({id:d.id,authorId:d.author_id,category:d.category,time:new Date(d.created_at).toLocaleDateString('en-IN'),text:d.body,tags:d.tags||[],likes:0,comments:0,shares:d.share_count||0}));return {posts:mappedPosts,profiles:mappedPeople};}catch{return {posts,profiles};}
}
export async function getJobs():Promise<Job[]>{if(!configured())return jobs;try{const sb=await createClient();const {data}=await sb.from('jobs').select('*,companies(name)').eq('status','published').order('created_at',{ascending:false});if(!data?.length)return jobs;return data.map((d:any)=>({id:d.id,title:d.title,company:d.companies?.name||'Maritime Company',rank:d.rank||'',vesselType:d.vessel_type||'Shore',contract:d.contract_duration||d.employment_type||'',salary:d.salary_display||[d.salary_min,d.salary_max,d.salary_currency].filter(Boolean).join(' '),joining:d.joining_date||'To be confirmed',experience:d.experience_required||'',location:d.location||'Worldwide',description:d.description,skills:d.skills_required||[],applicants:0,match:0}));}catch{return jobs;}}
export async function getGroups(){if(!configured())return groups;try{const sb=await createClient();const {data}=await sb.from('groups').select('*').eq('visibility','public').order('member_count',{ascending:false});return data?.length?data.map((d:any)=>({id:d.id,name:d.name,members:d.member_count||0,posts:'Active',description:d.description||''})):groups;}catch{return groups;}}
export async function getCourses():Promise<Course[]>{if(!configured())return courses;try{const sb=await createClient();const {data}=await sb.from('courses').select('*').eq('status','published').order('created_at',{ascending:false});return data?.length?data.map((d:any)=>({id:d.id,title:d.title,category:d.category,instructor:'Sea N Shore Academy',level:d.level||'All levels',lessons:0,duration:'Self-paced',rating:0,learners:0,price:Math.round((d.price_minor||0)/100),progress:0,description:d.description||'',tag:'Academy'})):courses;}catch{return courses;}}
export async function getMentors(){if(!configured())return mentors;try{const sb=await createClient();const {data}=await sb.from('mentor_profiles').select('*,profiles(full_name,verification_badge)').eq('active',true);return data?.length?data.map((d:any)=>({id:d.profile_id,name:d.profiles?.full_name||'Maritime Mentor',initials:(d.profiles?.full_name||'MM').split(' ').map((x:string)=>x[0]).slice(0,2).join(''),expertise:d.expertise||[],experience:d.experience_summary||'Industry experience',rating:Number(d.average_rating||0),reviews:d.review_count||0,price:Math.round((d.session_price_minor||0)/100),next:'View availability',bio:d.bio||'',verified:d.profiles?.verification_badge||'Verified Mentor'})):mentors;}catch{return mentors;}}
export async function getEvents(){if(!configured())return events;try{const sb=await createClient();const {data}=await sb.from('events').select('*').eq('status','published').order('starts_at',{ascending:true});return data?.length?data.map((d:any)=>({id:d.id,title:d.title,date:new Date(d.starts_at).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),time:new Date(d.starts_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}),type:d.event_type,speaker:Array.isArray(d.speakers)?d.speakers.map((x:any)=>x.name||x).join(' · '):'Maritime experts',attendees:0,mode:d.mode||d.location||'Online',description:d.description||''})):events;}catch{return events;}}
