import Link from 'next/link';
import { ArrowRight, BadgeCheck, BookOpenCheck, BriefcaseBusiness, Globe2, GraduationCap, Network, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { Logo } from '@/components/logo';

const modules=[
  ['Professional Network','A maritime-only feed for practical knowledge, career conversations, achievements and industry discussion.',Network],
  ['Verified Maritime Identity','Professional profiles built around rank, vessel experience, CoC, STCW, skills and career interests.',ShieldCheck],
  ['Careers Marketplace','Sea-going and shore roles with profile matching, application tracking and recruiter workflows.',BriefcaseBusiness],
  ['Sea N Shore Academy','SIRE 2.0, TMSA, leadership, shore transition, AI, digitalisation and future-skills learning.',GraduationCap],
  ['Mentors & Experts','Book vetted maritime leaders, lawyers, wellness experts and career mentors.',Users],
  ['Maritime AI','Context-aware career guidance, interview preparation, CV positioning and learning recommendations.',Sparkles]
] as const;
export default function Landing(){return <main className="min-h-screen overflow-hidden bg-[#f6fafc]">
  <header className="relative z-20 border-b border-white/10 bg-[#061f37] text-white"><div className="mx-auto flex h-20 max-w-[1380px] items-center justify-between px-5 lg:px-8"><div className="rounded-2xl bg-white px-3 py-2"><Logo/></div><nav className="hidden items-center gap-7 text-sm font-semibold text-white/70 md:flex"><a href="#ecosystem">Ecosystem</a><a href="#network">Network</a><a href="#careers">Careers</a><a href="#learning">Learning</a></nav><div className="flex items-center gap-2"><Link href="/login" className="sns-button border border-white/20 bg-white/5 px-4 py-2.5 text-sm text-white">Sign in</Link><Link href="/home" className="sns-button bg-white px-4 py-2.5 text-sm text-[#08233d]">Enter network <ArrowRight size={16}/></Link></div></div></header>
  <section className="sns-cover relative min-h-[690px] text-white"><div className="mx-auto grid max-w-[1380px] gap-12 px-5 py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-28"><div className="relative z-10"><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/7 px-3 py-2 text-xs font-bold uppercase tracking-[.12em] text-[#98d9e7]"><Globe2 size={15}/>The professional operating system for maritime careers</div><h1 className="font-display mt-7 max-w-[820px] text-5xl font-bold leading-[1.03] tracking-[-.045em] sm:text-6xl lg:text-[78px]">Your maritime career deserves a <span className="text-[#65d0e3]">network</span>, not just a job portal.</h1><p className="mt-7 max-w-[760px] text-lg leading-8 text-white/68 sm:text-xl">Connect with seafarers, shore leaders, companies, trainers and experts. Build reputation. Find the right role. Learn critical skills. Participate in the professional conversations shaping shipping.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/home" className="sns-button bg-white px-6 py-3.5 text-[#08233d]">Join Sea N Shore <ArrowRight size={17}/></Link><Link href="/jobs" className="sns-button border border-white/20 bg-white/7 px-6 py-3.5 text-white">Explore maritime careers</Link></div><div className="mt-12 grid max-w-[740px] grid-cols-2 gap-5 border-t border-white/10 pt-7 sm:grid-cols-4"><div><b className="text-2xl">38k+</b><span className="mt-1 block text-xs text-white/55">Professionals</span></div><div><b className="text-2xl">120+</b><span className="mt-1 block text-xs text-white/55">Industry experts</span></div><div><b className="text-2xl">860+</b><span className="mt-1 block text-xs text-white/55">Career opportunities</span></div><div><b className="text-2xl">34</b><span className="mt-1 block text-xs text-white/55">Countries represented</span></div></div></div>
  <div className="relative z-10 self-center"><div className="rounded-[28px] border border-white/12 bg-white/8 p-3 shadow-2xl backdrop-blur-xl"><div className="rounded-[22px] bg-[#f8fbfd] p-4 text-[#173b59]"><div className="flex items-center justify-between border-b border-[#e4ecf2] pb-3"><div className="text-sm font-black">Your professional feed</div><span className="sns-pill sns-pill-blue">Maritime only</span></div><div className="mt-4 rounded-2xl border border-[#dde7ee] bg-white p-4"><div className="flex items-start gap-3"><div className="sns-avatar sns-avatar-sm">PN</div><div><b className="text-sm">Priya Nair <span className="text-[#1167d8]">✓</span></b><div className="text-[11px] text-[#788b9a]">Chief Officer · LNG · 18 min</div></div></div><p className="mt-3 text-sm leading-6 text-[#4c667a]">5 common SIRE 2.0 observations I keep seeing during pre-vetting preparation...</p><div className="mt-3 flex gap-2"><span className="sns-pill">#SIRE2.0</span><span className="sns-pill">#Vetting</span></div></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-[#dde7ee] bg-white p-4"><div className="text-[11px] font-bold uppercase tracking-[.1em] text-[#778b9c]">Recommended role</div><div className="mt-2 text-sm font-black">Marine Superintendent</div><div className="mt-1 text-xs text-[#718699]">NorthStar Maritime · Mumbai</div><div className="mt-3 inline-flex rounded-full bg-[#ebf8f2] px-2 py-1 text-[11px] font-black text-[#13875d]">94% profile match</div></div><div className="rounded-2xl border border-[#dde7ee] bg-white p-4"><div className="text-[11px] font-bold uppercase tracking-[.1em] text-[#778b9c]">Continue learning</div><div className="mt-2 text-sm font-black">SIRE 2.0: Procedure to Evidence</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#e7eef3]"><div className="h-full w-[42%] rounded-full bg-[#1aa17a]"/></div><div className="mt-1 text-[11px] text-[#718699]">42% completed</div></div></div></div></div></div></div></section>
  <section id="ecosystem" className="mx-auto max-w-[1380px] px-5 py-20 lg:px-8"><div className="mx-auto max-w-3xl text-center"><div className="text-xs font-black uppercase tracking-[.14em] text-[#1167d8]">One maritime ecosystem</div><h2 className="font-display mt-3 text-4xl font-bold tracking-[-.04em] text-[#08233d] sm:text-5xl">Built around how maritime careers actually grow.</h2><p className="mt-5 text-lg leading-8 text-[#667f91]">Professional identity, relationships, learning and opportunities reinforce one another. Sea N Shore connects them in one daily network.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{modules.map(([title,copy,Icon])=><div key={title} className="sns-card p-6"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eaf3ff] text-[#1167d8]"><Icon size={21}/></div><h3 className="mt-5 text-lg font-black text-[#173b59]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#667f91]">{copy}</p></div>)}</div></section>
  <section id="network" className="border-y border-[#dfe8ef] bg-white"><div className="mx-auto grid max-w-[1380px] gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><span className="sns-pill sns-pill-blue">Professional network first</span><h2 className="font-display mt-5 text-4xl font-bold tracking-[-.04em] text-[#08233d]">A daily maritime network that becomes more valuable every time you contribute.</h2><p className="mt-5 text-lg leading-8 text-[#647c8e]">Posts, comments, questions, groups and professional reputation create a durable industry graph. Jobs and courses are connected to that identity instead of living in isolated portals.</p><div className="mt-7 space-y-3">{['Verified seafarer, company, mentor, trainer and expert badges','Role-specific maritime groups and technical discussions','Reputation points for useful posts, answers, mentoring and learning','Career interests and availability visible to the right recruiters'].map(x=><div key={x} className="flex gap-3 text-sm font-semibold text-[#31536d]"><BadgeCheck size={19} className="shrink-0 text-[#13875d]"/>{x}</div>)}</div></div><div className="rounded-[28px] bg-[#eff6fa] p-5"><div className="grid gap-4 sm:grid-cols-2"><div className="sns-card p-5"><Network size={23} className="text-[#1167d8]"/><div className="mt-4 text-3xl font-black text-[#08233d]">21.8k</div><div className="text-sm text-[#6b8192]">Monthly active professionals</div></div><div className="sns-card p-5"><BookOpenCheck size={23} className="text-[#1167d8]"/><div className="mt-4 text-3xl font-black text-[#08233d]">6.4k</div><div className="text-sm text-[#6b8192]">Course enrollments</div></div><div className="sns-card p-5"><BriefcaseBusiness size={23} className="text-[#1167d8]"/><div className="mt-4 text-3xl font-black text-[#08233d]">12.9k</div><div className="text-sm text-[#6b8192]">Job applications</div></div><div className="sns-card p-5"><Users size={23} className="text-[#1167d8]"/><div className="mt-4 text-3xl font-black text-[#08233d]">17.3k</div><div className="text-sm text-[#6b8192]">Shore-transition community</div></div></div></div></div></section>
  <footer className="bg-[#061f37] text-white"><div className="mx-auto flex max-w-[1380px] flex-col gap-6 px-5 py-10 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div className="rounded-xl bg-white px-3 py-2"><Logo/></div><div className="text-sm text-white/55">Sea N Shore Global Shipping Community · Built for maritime professionals worldwide.</div><Link href="/home" className="sns-button bg-white px-4 py-2.5 text-sm text-[#08233d]">Enter the network</Link></div></footer>
</main>}
