'use client';
import { useState } from 'react';
import { ArrowUp, Bot, Sparkles } from 'lucide-react';
import { currentUser } from '@/lib/data/seed';
import { recommendedRoles } from '@/lib/domain/recommendations';

type Msg={role:'user'|'ai';text:string};
function fallback(q:string){const lower=q.toLowerCase();if(lower.includes('shore')||lower.includes('career'))return `Based on a senior maritime profile, strong shore paths include ${recommendedRoles(currentUser).join(', ')}. Prioritise evidence of risk judgement, leadership, assurance and cross-functional decisions—not only sea-going responsibilities.`;if(lower.includes('sire'))return 'For SIRE 2.0, prepare around question intent, actual practice, evidence trails and human factors. Link the procedure to records, recent examples, familiarisation and what the responsible officer actually does.';if(lower.includes('cv'))return 'For a maritime CV, lead with target role positioning, vessel/rank depth, measurable outcomes, assurance exposure, certificates, incident or audit experience, and examples that translate shipboard judgement into shore value.';return 'I can help with maritime career paths, SIRE 2.0, interview preparation, CV positioning, regulations and learning recommendations. For regulatory decisions, production mode should cite the controlling official source and effective date.'}
export function AIAssistant(){const [messages,setMessages]=useState<Msg[]>([{role:'ai',text:'Welcome to Sea N Shore AI. Ask about shore careers, SIRE 2.0, interview preparation, maritime CVs or professional learning.'}]);const [q,setQ]=useState('');const send=async()=>{const text=q.trim();if(!text)return;setMessages(m=>[...m,{role:'user',text},{role:'ai',text:fallback(text)}]);setQ('')};return <div className="sns-card overflow-hidden"><div className="sns-cover flex min-h-[120px] items-end p-5 text-white"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.13em] text-[#8fd7e6]"><Sparkles size={15}/>Maritime intelligence</div><div className="mt-2 text-2xl font-black">Sea N Shore AI</div><div className="mt-1 max-w-xl text-sm text-white/70">Career guidance, learning recommendations and maritime knowledge—designed around professional context.</div></div></div><div className="h-[480px] space-y-3 overflow-y-auto bg-[#f7fafc] p-4">{messages.map((m,i)=><div key={i} className={`flex ${m.role==='user'?'justify-end':'justify-start'}`}>{m.role==='ai'&&<div className="mr-2 mt-1 grid h-8 w-8 place-items-center rounded-xl bg-[#0e4f82] text-white"><Bot size={16}/></div>}<div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.role==='user'?'bg-[#1167d8] text-white':'border border-[#dce7ef] bg-white text-[#29465d]'}`}>{m.text}</div></div>)}</div><div className="border-t border-[#dfe9f0] bg-white p-3"><div className="flex gap-2"><textarea value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} className="sns-input min-h-[48px] resize-none" placeholder="Ask a maritime question…"/><button onClick={send} className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#1167d8] text-white"><ArrowUp size={18}/></button></div><div className="mt-2 text-[10px] text-[#8a9ba9]">AI guidance should not replace controlling regulations, company procedures or qualified professional advice.</div></div></div>}
