'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { BadgeCheck, Bell, BookOpen, BriefcaseBusiness, Building2, CalendarDays, CircleUserRound, Compass, GraduationCap, HeartPulse, Home, Menu, MessageCircleMore, Search, Sparkles, Users, WandSparkles } from 'lucide-react';
import { Logo } from './logo';
import { Avatar } from './ui';
import { currentUser, type Profile } from '@/lib/data/seed';
import { useState } from 'react';

const main=[['/home','Home',Home],['/jobs','Jobs',BriefcaseBusiness],['/community','Community',Users],['/learn','Learn',GraduationCap],['/events','Events',CalendarDays],['/profile','Profile',CircleUserRound]] as const;
const more=[['/mentorship','Mentorship',MessageCircleMore],['/wellness','Wellness',HeartPulse],['/branding','Career Branding',WandSparkles],['/knowledge','Knowledge Hub',BookOpen],['/assistant','AI Maritime Assistant',Sparkles],['/recruiter','Recruiter Workspace',Building2],['/verification','Verification',BadgeCheck]] as const;
export function AppShell({children,profile=currentUser}:{children:React.ReactNode;profile?:Profile}){
  const path=usePathname(); const router=useRouter(); const [menu,setMenu]=useState(false); const [search,setSearch]=useState('');
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(search.trim())router.push(`/jobs?q=${encodeURIComponent(search.trim())}`)};
  return <div className="min-h-screen">
    <header className="sticky top-0 z-40 border-b border-[#dce6ee]/90 bg-white/90 backdrop-blur-xl">
      <div className="mx-auto flex h-[68px] max-w-[1500px] items-center gap-4 px-4 lg:px-6">
        <div className="w-[255px] shrink-0"><Logo /></div>
        <form onSubmit={submit} className="hidden max-w-[620px] flex-1 items-center rounded-2xl border border-[#dbe5ee] bg-[#f7fafc] px-3 md:flex"><Search size={17} className="text-[#7890a3]"/><input value={search} onChange={e=>setSearch(e.target.value)} className="h-10 flex-1 bg-transparent px-2 text-sm outline-none" placeholder="Search people, jobs, companies, courses…"/><span className="text-[11px] font-bold text-[#93a4b2]">⌘ K</span></form>
        <div className="ml-auto flex items-center gap-2"><Link href="/assistant" className="hidden rounded-xl p-2.5 text-[#526d82] hover:bg-[#f0f5f8] sm:block"><Sparkles size={19}/></Link><button className="relative rounded-xl p-2.5 text-[#526d82] hover:bg-[#f0f5f8]"><Bell size={19}/><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-[#e25757] ring-2 ring-white"/></button><Link href="/profile"><Avatar initials={profile.initials} size="sm"/></Link><button onClick={()=>setMenu(!menu)} className="rounded-xl p-2 lg:hidden"><Menu size={21}/></button></div>
      </div>
    </header>
    <div className="mx-auto grid max-w-[1500px] grid-cols-1 gap-5 px-3 py-5 lg:grid-cols-[255px_minmax(0,1fr)] lg:px-6 xl:grid-cols-[255px_minmax(0,760px)_330px]">
      <aside className={`${menu?'block':'hidden'} lg:block`}><nav className="sticky top-[88px] space-y-1 rounded-2xl border border-[#dce6ee] bg-white p-2 shadow-[0_8px_28px_rgba(8,35,61,.04)]">{main.map(([href,label,Icon])=><Link key={href} href={href} onClick={()=>setMenu(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${path===href?'bg-[#eaf3ff] text-[#0755b1]':'text-[#526d82] hover:bg-[#f5f8fa]'}`}><Icon size={18}/>{label}</Link>)}<div className="my-2 border-t border-[#edf2f5]"/>{more.map(([href,label,Icon])=><Link key={href} href={href} onClick={()=>setMenu(false)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold ${path===href?'bg-[#eaf3ff] text-[#0755b1]':'text-[#60788c] hover:bg-[#f5f8fa]'}`}><Icon size={17}/>{label}</Link>)}<div className="mt-2 rounded-xl bg-[#08233d] p-4 text-white"><div className="text-[11px] font-bold uppercase tracking-[.12em] text-[#8fc5d9]">Your reputation</div><div className="mt-1 text-lg font-black">Knowledge Leader</div><div className="mt-1 text-xs text-white/65">{profile.reputation.toLocaleString()} professional points</div></div></nav></aside>
      <main className="min-w-0">{children}</main>
      <RightRail profile={profile}/>
    </div>
    <nav className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-6 border-t border-[#dce6ee] bg-white px-1 py-1.5 lg:hidden">{main.map(([href,label,Icon])=><Link key={href} href={href} className={`flex flex-col items-center gap-1 rounded-xl py-1.5 text-[10px] font-bold ${path===href?'text-[#1167d8]':'text-[#74889a]'}`}><Icon size={18}/>{label}</Link>)}</nav>
  </div>
}
function RightRail({profile}:{profile:Profile}){return <aside className="hidden xl:block"><div className="sticky top-[88px] space-y-4"><div className="sns-card overflow-hidden"><div className="sns-cover h-16"/><div className="px-4 pb-4"><div className="-mt-6"><Avatar initials={profile.initials}/></div><div className="mt-2 font-black text-[#08233d]">{profile.name}</div><div className="text-xs text-[#718396]">{profile.role}</div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div><b className="block text-sm">8.4k</b><span className="text-[10px] text-[#7c90a0]">Connections</span></div><div><b className="block text-sm">21.4k</b><span className="text-[10px] text-[#7c90a0]">Followers</span></div><div><b className="block text-sm">5.4k</b><span className="text-[10px] text-[#7c90a0]">Reputation</span></div></div></div></div><div className="sns-card p-4"><div className="flex items-center justify-between"><div className="sns-section-title">Trending in maritime</div><span className="sns-pill sns-pill-green">Live</span></div><div className="mt-3 space-y-3">{['SIRE 2.0 evidence quality','Seafarer shore transition','Alternative fuels training','Maritime AI adoption','Crew wellbeing'].map((x,i)=><div key={x} className="flex gap-3"><span className="text-xs font-black text-[#9bb0c0]">0{i+1}</span><div><div className="text-sm font-bold text-[#294a65]"># {x}</div><div className="text-[11px] text-[#8295a5]">{284-i*31} conversations</div></div></div>)}</div></div><div className="sns-card p-4"><div className="flex items-center gap-2 text-sm font-black text-[#173b59]"><Compass size={17}/>Build your maritime graph</div><p className="mt-2 text-xs leading-5 text-[#728598]">Follow verified professionals, join role-specific groups and contribute useful answers to grow reputation.</p><Link href="/community" className="mt-3 inline-flex text-xs font-black text-[#1167d8]">Discover communities →</Link></div></div></aside>}
