'use client';
import { useState } from 'react';
import { BadgeCheck, Building2, FileCheck2, Fingerprint, ShieldCheck } from 'lucide-react';
import { Card } from '@/components/ui';
const methods=[
  {id:'certificate',title:'Certificate verification',copy:'Submit CoC, STCW or relevant professional certificates for review.',icon:FileCheck2},
  {id:'company',title:'Company email verification',copy:'Confirm employment or company representation using an approved corporate domain.',icon:Building2},
  {id:'identity',title:'Identity verification',copy:'Complete identity verification before receiving a trusted professional badge.',icon:Fingerprint}
] as const;
export default function VerificationPage(){const [submitted,setSubmitted]=useState<string[]>([]);return <div className="space-y-4"><div><div className="sns-page-title">Professional verification</div><p className="sns-page-copy mt-1">Build trust with evidence-based badges for seafarers, companies, experts, trainers and mentors.</p></div><Card className="overflow-hidden"><div className="sns-cover p-6 text-white"><div className="relative z-10"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.12em] text-[#a6dce7]"><ShieldCheck size={16}/>Trust layer</div><h1 className="mt-2 text-2xl font-black">Verified Seafarer · Company · Expert · Trainer · Mentor</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/70">Badges are issued only after the required evidence is reviewed. Verification status is designed to be visible across profiles, jobs, groups, courses and mentorship.</p></div></div></Card><div className="grid gap-4 md:grid-cols-3">{methods.map(m=>{const yes=submitted.includes(m.id);const Icon=m.icon;return <Card key={m.id} className="p-5"><Icon size={22} className="text-[#1167d8]"/><h2 className="mt-4 font-black text-[#173b59]">{m.title}</h2><p className="mt-2 min-h-[72px] text-sm leading-6 text-[#667f91]">{m.copy}</p><button onClick={()=>setSubmitted(yes?submitted:[...submitted,m.id])} className={`sns-button mt-4 w-full text-xs ${yes?'sns-button-secondary text-[#13875d]':'sns-button-primary'}`}>{yes?<><BadgeCheck size={15}/>Submitted for review</>:'Start verification'}</button></Card>})}</div><Card className="p-5"><div className="font-black text-[#173b59]">Verification principles</div><div className="mt-4 grid gap-3 sm:grid-cols-3">{['Private evidence storage','Admin audit trail','Revocable badge status'].map(x=><div key={x} className="rounded-xl bg-[#f6f9fb] p-3 text-sm font-bold text-[#526d82]">✓ {x}</div>)}</div></Card></div>}
